OUT_DIR: ""
SYSTEM:
  NUM_GPUS: 1
  NUM_WORKERS: 24
MODEL:
  IMAGE_BACKBONE: "efficient_s"
  EMBEDDER_TYPE_IMAGE_MODULE: "spatial"
  NORMALISE_EMBEDDING: True
  DECODER_SEMANTIC_CLASSES: 6
  DECODER_RESOLUTION: (256, 256)
  DESC_LENGTH: 256
  PANO_BB_EXTENSION_FACTOR: 1.2
  PREDICT_POSES: True
  PANO_ENCODE_DEPTH: False
  PANO_ENCODE_NORMALS: False
  LEARN_FOV: True
  LEARN_ASPECT: False
TRAIN:
  LR_MILESTONES: [12, 18]
  NUM_EPOCHS: 25
  INITIAL_LR: 0.00025
  LR_GAMMA: 0.5
  BATCH_SIZE: 40
  TEST_EVERY: 1
  NUM_NEAR_SAMPLES: 4
  NUM_FAR_SAMPLES: 1
  PANO_POSE_OFFSETS: [1.4, 1.4, 0.3]
  RETRAIN_DECODER: True
  FILTER_PANO_SAMPLES: True
TEST:
  POSE_SAMPLE_STEP: 1200
RENDER:
  PANO_SIZE: (128, 256)
  IMG_SIZE: (256, 256)
POSE_REFINE:
  MAX_ITERS: 0
INPUT:
  IMG_SIZE: (256, 256)
DATASET:
  PATH: "/mnt/datasets/Structured3D"
  NAME: "S3D"
  TEST_LIGHTING: ['raw']
  TEST_SET_FURNITURE: ['empty']
  TRAIN_LIGHTING: ['raw']
  TRAIN_FURNITURE: ['empty', 'full']
  USE_PREPARED_DATA: True
  PREPARED_DATA_PATH: "pickle"
  PREPARED_DATA_PATH_TEST: "pickle_test"
  PERSP_FROM_PANO: True
  PERSP_FROM_PANO_RANGE: [180, 10, 10]
  PERSP_FROM_PANO_FOV: 90.0
  MIN_AVERAGE_DISTANCE: 0.0
  PERSP_FROM_PANO_FILTER_VALID_YAW: True
  S3D_NO_PERSP_IMAGES: False
  PERSP_FROM_PANO_CORRECT_ROLL: True
