OUT_DIR: ""
SYSTEM:
  NUM_GPUS: 1
  NUM_WORKERS: 10
MODEL:
  IMAGE_BACKBONE: "efficient_s"
  EMBEDDER_TYPE_IMAGE_MODULE: "spatial"
  NORMALISE_EMBEDDING: True
  DECODER_SEMANTIC_CLASSES: 6
  DECODER_RESOLUTION: (256, 256)
  DESC_LENGTH: 256
  PANO_BB_EXTENSION_FACTOR: 1.2
  PREDICT_POSES: True
  PANO_ENCODE_DEPTH: False
  PANO_ENCODE_NORMALS: False
  LEARN_FOV: True
  LEARN_ASPECT: False
TRAIN:
  LR_MILESTONES: [12, 18]
  NUM_EPOCHS: 25
  INITIAL_LR: 0.00025
  LR_GAMMA: 0.5
  BATCH_SIZE: 1
  TEST_EVERY: 1
  NUM_NEAR_SAMPLES: 1
  NUM_FAR_SAMPLES: 0
  PANO_POSE_OFFSETS: [1.4, 1.4, 0.3]
  RETRAIN_DECODER: True
  FILTER_PANO_SAMPLES: False
TEST:
  POSE_SAMPLE_STEP: 1200
  CAMERA_HEIGHT: 1400
  ADVANCED_POSE_SAMPLING: False
RENDER:
  PANO_SIZE: (128, 256)
  IMG_SIZE: (320, 320)
  FIX_SEED: True
POSE_REFINE:
  MAX_ITERS: 0
INPUT:
  IMG_SIZE: (256, 256)
DATASET:
  PATH: "external/zind_sample_tour"
  NAME: "Zillow"
  TEST_LIGHTING: ['raw']
  TEST_SET_FURNITURE: ['full_90_10_10']
  TRAIN_LIGHTING: ['raw']
  TRAIN_FURNITURE: ['full']
  USE_PREPARED_DATA: True
  PREPARED_DATA_PATH: "pickle"
  PREPARED_DATA_PATH_TEST: "pickle_eval"
  PERSP_FROM_PANO: False
  PERSP_FROM_PANO_RANGE: [180, 10, 10]
  PERSP_FROM_PANO_FOV: 90.0
  MIN_AVERAGE_DISTANCE: 0.0
  CACHE_TEST_BATCHES: False
  PERSP_FROM_PANO_CORRECT_ROLL: True
